name: Update Visitor Count

on:
  push:
    branches:
      - main

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current visitor count
        id: read_count
        run: |
          if [ ! -f visitor_count.txt ]; then echo "0" > visitor_count.txt; fi
          count=$(cat visitor_count.txt)
          echo "::set-output name=count::$count"

      - name: Increment visitor count
        id: increment_count
        run: |
          new_count=$(( ${{ steps.read_count.outputs.count }} + 1 ))
          echo "::set-output name=new_count::$new_count"

      - name: Update visitor count file
        run: echo "${{ steps.increment_count.outputs.new_count }}" > visitor_count.txt

      - name: Commit updated visitor count
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add visitor_count.txt
          git commit -m "Update visitor count to ${{ steps.increment_count.outputs.new_count }}"
          git push
